#+TITLE: Обзор архитектура
#+AUTHOR: Gleb Kanterov <gleb@kanterov.ru>

* Обзор архитектуры

В данном разделе кратко изложены основные компоненты системы.

Каркас приложения содержит 2 точки расширения (/extension points/):
*ru.nsu.ccfit.resync.storage* и *ru.nsu.ccfit.resync.prefs*. Плагин
будет предоставлять расширения для *storage* и *prefs*, для
синхронизации настроек JDT и поддержки Github, но точки расширения
могут дополняться и другими плагинами, например, для поддержки
настроек /Scala IDE/ и хранения их в /LDAP/.

Плагин, будет предоставлять команду (/command/), которая будет
вызывать диалоговое окно, для выбора настроек синхронизации, в
последствии, создавая задачу (/job/), которая будет импорт или экспорт
настроек.

** Точка расширения ru.nsu.ccfit.resync.storage

Позволяет добавлять поддержку новых типов хранилищ настроек (например,
/gist/ на /Github/).

Расширение задается реализацией интерфейса фабрики хранилищ настроек
*ru.nsu.ccfit.resync.storage.PreferenceStorageFactory*. Подробная
информация содержится в /javadoc/.

** Точка расширения ru.nsu.ccfit.resync.prefs

Позволяет добавлять поддержку новых типов настроек, суда входят методы
для экспортирования и импорта настроек. Например, поддержка настроек
форматирования.

Расширение задается реализацией интерфейса поставщика настроек.
*ru.nsu.ccfit.resync.prefs.PreferenceProvider*. Подробная информация
содержится в /javadoc/.

** Развертывание

Для установки плагина в результате процесса сборки приложения будет
сгенерирован p2-репозиторий (/p2-repository/), с которого можно
установить приложение при помощи /Eclipse/. Данный репозиторий будет
публично доступен в Интернет по окончанию реализации основной
функциональности

